# Generated by Django 2.2.28 on 2023-07-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('Corporate Sponsor Members', 'corpsponsor'), ('Corporate Members', 'corpmember'), ('Individual Members', 'indmember')], max_length=30),
        ),
    ]
