# Generated by Django 2.2.28 on 2023-07-22 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20230722_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Corporate Sponsor Members', 'corpsponsor'), ('Corporate Members', 'corpmember'), ('Individual Members', 'indmember')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Membership'),
        ),
    ]
