# Generated by Django 2.2.28 on 2023-07-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20230722_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='strip_plan_id',
            new_name='stripe_plan_id',
        ),
        migrations.AddField(
            model_name='usermembership',
            name='payment_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
