# Generated by Django 2.2.28 on 2023-07-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20230723_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Корпоративный спонсор', 'corpsponsor'), ('Корпоративный член', 'corpmember'), ('Физическое лицо', 'indmember')], max_length=30),
        ),
    ]
