# Generated by Django 2.2.28 on 2023-07-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField(help_text='Текст вашего поста', verbose_name='Текст')),
                ('pub_date', models.DateField(db_index=True, verbose_name='Дата события')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': ('Новость',),
                'verbose_name_plural': 'Новости',
                'ordering': ('-pub_date',),
            },
        ),
    ]
