# Generated by Django 2.2.28 on 2023-07-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название мероприятия')),
                ('text', models.TextField(help_text='Описание вашему мероприятия', verbose_name='Текст')),
                ('pub_date', models.DateField(db_index=True, verbose_name='Дата события')),
                ('image', models.ImageField(blank=True, upload_to='events/', verbose_name='Фотография')),
                ('url', models.URLField(blank=True, help_text='Ссылка регистрации на событие', max_length=255, verbose_name='Ссылка регистрации')),
            ],
            options={
                'verbose_name': ('Событие',),
                'verbose_name_plural': 'События',
                'ordering': ('-pub_date',),
            },
        ),
    ]
